backend:
  name: git-gateway
  branch: master

media_folder: static/uploads
public_folder: /uploads

display_url: https://echolacombe.ca/
logo_url: https://echolacombe.ca/images/logo.png

collections:
  - name: 'content'
    label: 'Content'
    delete: false
    editor:
      preview: false
    files:
      - name: 'data'
        label: 'Data'
        file: 'cms/data.json'
        fields:
          - { name: 'domainName', label: 'Domain Name', widget: 'string' }
          - { name: 'contactEmail', label: 'Contact Email', widget: 'string' }
          - { name: 'contactPhone', label: 'Contact Phone Number', widget: 'string' }
          - { name: 'contactPhoneRaw', label: 'Contact Phone Number Raw', widget: 'string' }
          - { name: 'seoDescription', label: 'SEO Description', widget: 'text' }
          - { name: 'seoTitle', label: 'SEO Title', widget: 'string' }

      - name: 'gallery'
        label: 'Gallery'
        file: 'cms/gallery.json'
        fields:
          - name: 'items'
            label: 'Gallery Items'
            label_singular: 'Gallery Item'
            widget: 'list'
            fields:
              - { name: 'title', label: 'Gallery Item Title', widget: 'string' }
              - { name: 'image', label: 'Gallery Item Image', widget: 'image' }

      - name: 'news'
        label: 'News'
        file: 'cms/news.json'
        fields:
          - name: 'items'
            label: 'News Items'
            label_singular: 'News Item'
            widget: 'list'
            fields:
              - { name: 'title', label: 'News Item Title', widget: 'string' }
              - { name: 'file', label: 'News Item File', widget: 'file' }
              - { name: 'url', label: 'News Item External URL', widget: 'string' }

      - name: 'food-rescue'
        label: 'Food Rescue'
        file: 'cms/food-rescue.json'
        fields:
          - { name: 'contactName', label: 'Contact Name', widget: 'string' }
          - { name: 'contactPhone', label: 'Contact Phone Number', widget: 'string' }
          - { name: 'contactPhoneRaw', label: 'Contact Phone Number Raw', widget: 'string' }
          - { name: 'contactEmail', label: 'Contact Email', widget: 'string' }
          - name: 'sections'
            label: 'Sections'
            label_singular: 'Section'
            widget: 'list'
            fields:
              - { name: 'title', label: 'Section Title', widget: 'string' }
              - { name: 'content', label: 'Section Content', widget: 'markdown' }
