backend:
  name: git-gateway
  branch: master

media_folder: static/images/uploads
public_folder: /images/uploads

display_url: https://echolacombe.ca/
logo_url: https://echolacombe.ca/images/logo.png

collections:
  - name: 'content'
    label: 'Content'
    delete: false
    editor:
      preview: false
    files:
      - name: 'data'
        label: 'Data'
        file: 'cms/data.json'
        fields:
          - { name: 'domainName', label: 'Domain Name', widget: 'string' }
          - { name: 'contactEmail', label: 'Email', widget: 'string' }
          - { name: 'contactPhone', label: 'Phone Number', widget: 'string' }
          - { name: 'contactPhoneRaw', label: 'Phone Number Raw', widget: 'string' }
          - { name: 'pageHomeHeroTitle', label: 'Page Home Hero Title', widget: 'string' }
          - { name: 'pageHomeHeroSubtitle', label: 'Page Home Hero Subtitle', widget: 'string' }
          - { name: 'seoDescription', label: 'SEO Description', widget: 'text' }
          - { name: 'seoTitle', label: 'SEO Title', widget: 'string' }

      - name: 'gallery'
        label: 'Gallery'
        file: 'cms/gallery.json'
        fields:
          - name: 'items'
            label: 'Gallery Items'
            label_singular: 'Gallery Item'
            widget: 'list'
            fields:
              - { name: 'title', label: 'Gallery Item Title', widget: 'string' }
              - { name: 'image', label: 'Gallery Item Image', widget: 'image' }
